// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type AppAccount struct {
	Email    string
	Username string
	Password string
}

type AppWallet struct {
	Email    string
	Currency string
	Balance  float32
}
