// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO app.account (email, username, password)
VALUES ($1, $2, $3)
RETURNING email, username, password
`

type CreateAccountParams struct {
	Email    string
	Username string
	Password string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (AppAccount, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Email, arg.Username, arg.Password)
	var i AppAccount
	err := row.Scan(&i.Email, &i.Username, &i.Password)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT email, username, password
FROM app.account
WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (AppAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i AppAccount
	err := row.Scan(&i.Email, &i.Username, &i.Password)
	return i, err
}

const isAccountExistsByEmail = `-- name: IsAccountExistsByEmail :one
SELECT EXISTS (
    SELECT 1 FROM app.account WHERE email = $1
)
`

func (q *Queries) IsAccountExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isAccountExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isAccountExistsByUsername = `-- name: IsAccountExistsByUsername :one
SELECT EXISTS (
    SELECT 1 FROM app.account WHERE username = $1
)
`

func (q *Queries) IsAccountExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, isAccountExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
